config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'signup' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  resources :genes
  resources :analyses do
    member do
      get 'queue', to: 'analyses#queue'
    end
  end
end

app/controllers/sbadmin_controller.rb
class SbadminController < ApplicationController
  layout 'sb-admin/sb-admin'
end

app/views/layouts/sb-admin/_footer.html.erb
<footer class="sticky-footer">
  <div class="container">
      <!-- To the right -->
      <div class="float-right hidden-xs">
        <b>Version</b> 0.1.3
      </div>
      <!-- Default to the left -->
      <strong>Copyright &copy; 2019 <a href="http://neemiasvf.me">Neemias Freitas</a>.</strong> All rights reserved.
  </div>
</footer>

app/views/layouts/sb-admin/_logout_modal.html.erb
<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="logoutModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
        <%= link_to 'Logout', destroy_user_session_path, class: 'btn btn-danger', method: :delete %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/sb-admin/_navbar.html.erb
<!-- Navigation Menu -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
  <%= link_to 'PERails', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
        <%= link_to root_path, class: 'nav-link' do %>
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span class="nav-link-text">Dashboard</span>
        <% end %>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Genes">
        <%= link_to genes_path, class: 'nav-link' do %>
          <i class="fas fa-fw fa-flask"></i>
          <span class="nav-link-text">Genes</span>
        <% end %>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Analyses">
        <%= link_to analyses_path, class: 'nav-link' do %>
          <i class="fas fa-fw fa-cogs"></i>
          <span class="nav-link-text">Analyses</span>
        <% end %>
      </li>
    </ul>
    <ul class="navbar-nav sidenav-toggler">
      <li class="nav-item">
        <a class="nav-link text-center" id="sidenavToggler">
          <i class="fas fa-fw fa-angle-left"></i>
        </a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" data-toggle="modal" data-target="#logoutModal">
          <i class="fas fa-fw fa-sign-out-alt"></i>Logout</a>
      </li>
    </ul>
  </div>
</nav>
<!-- Navigation Menu -->

app/views/layouts/sb-admin/sb-admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <%= csrf_meta_tags %>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title><%= yield :title %></title>
  </head>

  <body class='fixed-nav sticky-footer bg-dark" id="page-top"'>
    <%= render partial: 'layouts/sb-admin/navbar' %>
    <!-- Content Wrapper. Contains page content -->
    <div class='content-wrapper'>
      <!-- Content Header (Page header) -->
      <div class="container-fluid">
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>

        <h1>
          <%= yield :page_header %>
          <small><%= yield :optional_description %></small>
          <div class="float-right">
            <%= yield :queue_button %>
            <%= yield :new_button %>
            <%= yield :edit_button %>
            <%= yield :back_button %>
          </div>
        </h1>

        <%= yield %>

        <%= render 'layouts/sb-admin/footer' %>
      </div>
    </div>
    <!-- /.content-wrapper -->
  </body>

  <%= render partial: 'layouts/sb-admin/logout_modal' %>
</html>